config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :foodstalls

  resources :tasks

end

app/models/foodstall.rb
class Foodstall < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foodstalls_controller.rb
class FoodstallsController < ApplicationController
  before_action :set_foodstall, only: [:show, :edit, :update, :destroy]

  # GET /foodstalls
  # GET /foodstalls.json
  def index
    @foodstalls = Foodstall.all
  end

  # GET /foodstalls/1
  # GET /foodstalls/1.json
  def show
  end

  # GET /foodstalls/new
  def new
    @foodstall = Foodstall.new
  end

  # GET /foodstalls/1/edit
  def edit
  end

  # POST /foodstalls
  # POST /foodstalls.json
  def create
    @foodstall = Foodstall.new(foodstall_params)

    respond_to do |format|
      if @foodstall.save
        format.html { redirect_to @foodstall, notice: 'Foodstall was successfully created.' }
        format.json { render :show, status: :created, location: @foodstall }
      else
        format.html { render :new }
        format.json { render json: @foodstall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodstalls/1
  # PATCH/PUT /foodstalls/1.json
  def update
    respond_to do |format|
      if @foodstall.update(foodstall_params)
        format.html { redirect_to @foodstall, notice: 'Foodstall was successfully updated.' }
        format.json { render :show, status: :ok, location: @foodstall }
      else
        format.html { render :edit }
        format.json { render json: @foodstall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodstalls/1
  # DELETE /foodstalls/1.json
  def destroy
    @foodstall.destroy
    respond_to do |format|
      format.html { redirect_to foodstalls_url, notice: 'Foodstall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodstall
      @foodstall = Foodstall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foodstall_params
      params.require(:foodstall).permit(:food, :price)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    # render :text => "contoh"
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :state)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodstalls_helper.rb
module FoodstallsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foodstalls/_form.html.erb
<%= form_for(@foodstall) do |f| %>
  <% if @foodstall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foodstall.errors.count, "error") %> prohibited this foodstall from being saved:</h2>

      <ul>
      <% @foodstall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food %><br>
    <%= f.text_field :food %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foodstalls/edit.html.erb
<h1>Editing foodstall</h1>

<%= render 'form' %>

<%= link_to 'Show', @foodstall %> |
<%= link_to 'Back', foodstalls_path %>

app/views/foodstalls/index.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="foodstall.css">
</head>
<body>
<h1>Listing foodstalls</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foodstalls.each do |foodstall| %>
      <tr>
        <td><%= foodstall.food %></td>
        <td><%= foodstall.price %></td>
        <td><%= link_to 'Show', foodstall %></td>
        <td><%= link_to 'Edit', edit_foodstall_path(foodstall) %></td>
        <td><%= link_to 'Destroy', foodstall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foodstall', new_foodstall_path %>
</body>

app/views/foodstalls/new.html.erb
<h1>New foodstall</h1>

<%= render 'form' %>

<%= link_to 'Back', foodstalls_path %>

app/views/foodstalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @foodstall.food %>
</p>

<p>
  <strong>Price:</strong>
  <%= @foodstall.price %>
</p>

<%= link_to 'Edit', edit_foodstall_path(@foodstall) %> |
<%= link_to 'Back', foodstalls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

@@@ header @@@
<%= yield %>
@@@ footer @@@

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<head>
<link rel="stylesheets" type="text/css" href="task.css.scss">
</head>
<body>
<h1>Senarai Tugasan</h1>

<table>
  <thead>
    <tr>
      <th>Tajuk</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.state %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

<br><a href="/users"> Link ke User </a>
<br><%= link_to "Link ke Users menggunakan link_to", new_user_path%></br><br>
</body>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tajuk:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.state %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>